url: "https://int-prob.github.io"

name: Integrable Probability FRG
description: Integrable Probability Focused Research Group
teaser: /img/paths.jpg

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

paginate: 10
paginate_path: "blog/page:num"
permalink: pretty
