url: "http://frg.int-prob.org"

name: Integrable Probability FRG
description: Integrable Probability Focused Research Group

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

paginate: 10
paginate_path: "posts/page:num"
permalink: pretty
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-redirect-from

hlcolor: "#FFE099"
